"""
core/filesystem_photos.py

Filesystem-based Photos API for MPD v2 — vendor-neutral, reads directly
from the album folders under PHOTO_PATH_SHARED / personal paths.

Implements the three methods that router handlers expect:
  list_folders()              → list of {id, name}
  list_photos(folder_id)      → list of {id, filename, additional}
  list_items(folder_id, type) → list of {id, filename, additional}
  get_thumbnail(id, cache_key, size) → bytes (Pillow-generated, cached)

Thumbnails live outside the photo trees in THUMB_CACHE_DIR/fs/.
Cache key = sha1(absolute_source_path + mtime_ns) → invalidates automatically.
"""

import hashlib
import io
import logging
from pathlib import Path
from typing import List, Dict, Optional

from PIL import Image, ImageOps

from config import THUMB_CACHE_DIR
from core.media_types import (PHOTO_EXTS as _PHOTO_EXTS,
                              VIDEO_EXTS as _VIDEO_EXTS,
                              MEDIA_EXTS as _MEDIA_EXTS)

logger = logging.getLogger(__name__)

_CACHE_SUBDIR = "fs"
_SIZES = {"sm": 200, "m": 400, "xl": 1200}


class FilesystemPhotosAPI:

    def __init__(self, base: Path):
        self.base = Path(base).resolve()

    # ── Listing ───────────────────────────────────────────────────

    def list_folders(self) -> List[Dict]:
        """Top-level subdirectories of base/, sorted by name. Hidden dirs
        (`.something`) are skipped so backup/system folders never surface."""
        if not self.base.is_dir():
            return []
        out = []
        for entry in sorted(self.base.iterdir()):
            if entry.is_dir() and not entry.name.startswith("."):
                out.append({"id": entry.name, "name": entry.name})
        return out

    def list_photos(self, folder_id) -> List[Dict]:
        """Photo files (still images) inside one album folder."""
        return self._list(folder_id, _PHOTO_EXTS)

    def list_items(self, folder_id, item_type: Optional[str] = None) -> List[Dict]:
        """All media (photos + videos) by default; filter via item_type."""
        if item_type == "photo":
            return self._list(folder_id, _PHOTO_EXTS)
        if item_type == "video":
            return self._list(folder_id, _VIDEO_EXTS)
        return self._list(folder_id, _MEDIA_EXTS)

    def _list(self, folder_id, exts: set) -> List[Dict]:
        """Files in one album folder filtered by extension set. Goes through
        `_safe_subdir`, so any caller-supplied path-traversal attempt
        ('../foo', '/etc/passwd') yields an empty list, never an exception."""
        folder = self._safe_subdir(str(folder_id))
        if folder is None:
            return []
        items = []
        for f in sorted(folder.iterdir()):
            if not f.is_file():
                continue
            if f.suffix.lower() not in exts:
                continue
            items.append({
                "id"      : f"{folder.name}/{f.name}",
                "filename": f.name,
                "additional": {
                    "thumbnail": {"cache_key": ""},
                },
            })
        return items

    # ── Thumbnail ─────────────────────────────────────────────────

    def get_thumbnail(self, photo_id, cache_key: str, size: str = "m") -> bytes:
        """
        photo_id is "{album}/{filename}" (as generated by _list() above).
        """
        if size not in _SIZES:
            size = "m"

        src = self._safe_file(str(photo_id))
        if src is None:
            raise FileNotFoundError(f"File not found or access denied: {photo_id}")

        cache_file = self._cache_path(src, size)
        if cache_file.exists():
            try:
                return cache_file.read_bytes()
            except OSError:
                pass  # cache broken → regenerate

        target = _SIZES[size]
        with Image.open(src) as img:
            img = ImageOps.exif_transpose(img)
            img.thumbnail((target, target), Image.Resampling.LANCZOS)
            if img.mode not in ("RGB", "L"):
                img = img.convert("RGB")
            buf = io.BytesIO()
            img.save(buf, format="JPEG", quality=85, optimize=True)
            data = buf.getvalue()

        try:
            cache_file.parent.mkdir(parents=True, exist_ok=True)
            cache_file.write_bytes(data)
        except OSError as e:
            logger.warning("Thumbnail cache write failed (%s): %s", cache_file, e)

        return data

    # ── Path-traversal protection ─────────────────────────────────

    def _safe_subdir(self, name: str) -> Optional[Path]:
        """Allows only subdirectories directly under base."""
        candidate = (self.base / name).resolve()
        if not candidate.is_relative_to(self.base):
            logger.warning("Path-traversal attempt (folder): %s", name)
            return None
        if not candidate.is_dir():
            return None
        if candidate == self.base:
            return None
        return candidate

    def _safe_file(self, rel_path: str) -> Optional[Path]:
        """Allows only files inside base/."""
        candidate = (self.base / rel_path).resolve()
        if not candidate.is_relative_to(self.base):
            logger.warning("Path-traversal attempt (file): %s", rel_path)
            return None
        if not candidate.is_file():
            return None
        return candidate

    def _cache_path(self, src: Path, size: str) -> Path:
        """JPEG thumb cache path for the legacy size codes (s/m/l). Same
        sha1(path+mtime) scheme as `core.thumb_pipeline`, but stored under
        a separate subdir so the two pipelines cannot collide."""
        try:
            mtime = src.stat().st_mtime_ns
        except OSError:
            mtime = 0
        key = hashlib.sha1(f"{src.resolve()}:{mtime}".encode("utf-8")).hexdigest()
        return THUMB_CACHE_DIR / _CACHE_SUBDIR / size / key[:2] / f"{key}.jpg"
